### ISSUE TITLE
Chapter 12. Error handling. Add info about js global error handlers 

### ISSUE THREAD

**Issue by olegKusov** [bespoyasov/refactor-like-a-superhero#14]
In our project we have global error handler for all errors. It's pretty easy to handle because we have one entity for Error handling. If something goes wrong in Error handling we going to ErrorService and work only with this entity.

We throw all errors (panic errors) and they catched by listeners. 

`class ErrorService {
   errors: ProjectError[] = [];
   constructor (window) {
      this.global = window;
    }
   
    listen() {
      global.addEventListener('error', (e) => {
        
        // error object creation and pushing error to errors array. We can add additional logic (e.g. counter of errors if there is multiple same errors on page, sending data to Sentry and etc.)
      })

      global.addEventListener('unhandledRejection', (e) => {
        //same here
      })
    
    }
}

//at root level of app
const errorService = new ErrorService(window);
errorService.listen(); 
`

**Comment by bespoyasov** [comment]
Hi! Thanks for commenting!

I believe the [“Last Resort Handlers” section](https://github.com/bespoyasov/refactor-like-a-superhero-online-book/blob/main/manuscript-en/12-error-handling.md#last-resort-handlers) already has this idea:

> At the entire application or web page level, we catch all the errors and panics not handled before.

I'm not sure we should describe particular implementation details for this level because constraints for different applications may vary. But the meaning, the goals, and some recommendations (e.g., about capturing stack trace or analytics) are expressed in the section.

As an option, if it's important to mention the `error` and `unhandledRejection` events, we can add them into the side note at the end of the section. It can be an additional recommendation like the description of Error Boundaries in React.

What do you think about it?
Maybe I miss something important?

**Comment by bespoyasov** [comment]
As for using just _one handler for all errors_, I wouldn’t recommend that as a default way to do handling, because it limits abilities for handling different kinds of errors differently.

Depending on the project requirements, developers might need to act on expected and unexpected errors (or low- and high-level errors for that matter) in different ways. (Like, say, for handling form validation and network errors.) If there’s only one entity, the developers then need to somehow identify _where, when, and what_ happened. So we lose the context of the error.

The lack of context makes it unclear where and how to handle the error. With the lost context, we either have to check for the same errors again somewhere else or lose information in the error message for the user or consuming function. Duplicate checks make the code noisy. Incomplete or incorrect information makes the result unreliable. Mixing expected and unexpected error, in general, erases the border between expected and unexpected behavior of the program.

A single global error handler might be convenient in some cases. For example, if we have only panics or only expected errors that should be handled equally throughout the project. But in such a case, the “handlers hierarchy” will just shrink to a single layer anyway.

For reducing code duplication in the handlers we can use various tools, like the decorator pattern or a form of inversion of control, e.g., architectural or framework constraints.

So I can't really encourage using a single handler as a “default” way of handling errors. However, if you have an idea for mentioning it as _one of the options_ to do error handling, we can come up with a side note for the text.

**Comment by olegKusov** [comment]
Thank you for answer!
